APP_NAME={{name}}-api

.PHONY: gen dev build test lint format check

gen:
	pnpm run gen

dev:
	pnpm run dev

build:
	pnpm run build

test:
	pnpm run test

lint:
	pnpm run lint

format:
	pnpm run format

check:
	pnpm run check
