// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apigen

// CreateWatchInput defines model for CreateWatchInput.
type CreateWatchInput struct {
	Name     string `json:"name"`
	Selector string `json:"selector"`
	Url      string `json:"url"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// UpdateWatchInput defines model for UpdateWatchInput.
type UpdateWatchInput struct {
	Name     *string `json:"name,omitempty"`
	Selector *string `json:"selector,omitempty"`
	Url      *string `json:"url,omitempty"`
}

// Watch defines model for Watch.
type Watch struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Selector string `json:"selector"`
	Url      string `json:"url"`
}

// WatchId defines model for WatchId.
type WatchId = int64

// CreateWatchJSONRequestBody defines body for CreateWatch for application/json ContentType.
type CreateWatchJSONRequestBody = CreateWatchInput

// UpdateWatchByIdJSONRequestBody defines body for UpdateWatchById for application/json ContentType.
type UpdateWatchByIdJSONRequestBody = UpdateWatchInput
